# https://firehydrant.io/blog/develop-a-go-app-with-docker-compose/
#  docker compose run --rm app air init
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/webapp"
  cmd = "go build -o ./tmp/webapp ./cmd/web"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "data"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "postgresql"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false